FROM maven as build
RUN mkdir -p /app
WORKDIR /app
ADD . /app
RUN mvn clean install
FROM openjdk:8
COPY --from=build /app/target/SpringRestApi.jar /app/target/SpringRestApi.jar
EXPOSE 8087
ENTRYPOINT ["java", "-jar", "/app/target/SpringRestApi.jar"]